import { insertSeedMeals } from '../database/mealRepository';
import { db } from '../database/db';

const seedMeals = [
  // === BREAKFAST-ORIENTED (18 dishes) ===
  { name: 'Tapsilog (Beef Tapa + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🍳', ingredients: JSON.stringify([{ name: 'Beef tapa', quantity: '200g' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }, { name: 'Vinegar', quantity: '2 tbsp' }, { name: 'Soy sauce', quantity: '2 tbsp' }]), steps: JSON.stringify(['Marinate beef in soy sauce, vinegar, and garlic overnight.', 'Pan-fry beef tapa until cooked.', 'Make garlic fried rice.', 'Fry egg sunny-side up.', 'Serve with vinegar dipping sauce.']), calories: 550 },
  { name: 'Tosilog (Tocino + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🥓', ingredients: JSON.stringify([{ name: 'Tocino (cured pork)', quantity: '200g' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Pan-fry tocino until caramelized and cooked through.', 'Make garlic fried rice.', 'Fry egg.', 'Serve together on a plate.']), calories: 600 },
  { name: 'Longsilog (Longganisa + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🌭', ingredients: JSON.stringify([{ name: 'Longganisa sausage', quantity: '4 pieces' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }, { name: 'Vinegar', quantity: 'for dipping' }]), steps: JSON.stringify(['Pan-fry longganisa in a bit of water until water evaporates, then fry in its own oil.', 'Make garlic fried rice.', 'Fry egg.', 'Serve with vinegar dipping sauce.']), calories: 580 },
  { name: 'Dangsilog (Daing + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 25, difficulty: 'medium', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Daing na bangus (marinated milkfish)', quantity: '1 piece' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Pan-fry daing until golden and crispy on both sides.', 'Make garlic fried rice.', 'Fry egg.', 'Serve immediately.']), calories: 500 },
  { name: 'Spamsilog (Spam + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🥫', ingredients: JSON.stringify([{ name: 'Spam', quantity: '4 slices' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Pan-fry Spam slices until crispy on edges.', 'Make garlic fried rice.', 'Fry egg.', 'Serve together.']), calories: 520 },
  { name: 'Cornedsilog (Corned Beef + Garlic Rice + Egg)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Corned beef', quantity: '1 can' }, { name: 'Onion', quantity: '1, minced' }, { name: 'Garlic fried rice', quantity: '1 cup' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Sauté onion in oil.', 'Add corned beef and cook until browned.', 'Make garlic fried rice.', 'Fry egg.', 'Serve together.']), calories: 540 },
  { name: 'Adobong Manok sa Gata', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🍗', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '500g' }, { name: 'Coconut milk', quantity: '1 cup' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Vinegar', quantity: '2 tbsp' }, { name: 'Garlic', quantity: '4 cloves' }]), steps: JSON.stringify(['Sauté garlic.', 'Add chicken and cook until browned.', 'Add soy sauce, vinegar, and coconut milk.', 'Simmer 30 minutes until tender.', 'Serve over rice.']), calories: 520 },
  { name: 'Chicken Arroz Caldo', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'medium', emoji: '🥣', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '300g' }, { name: 'Rice', quantity: '1 cup' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Fish sauce', quantity: '2 tbsp' }, { name: 'Spring onions', quantity: 'for garnish' }]), steps: JSON.stringify(['Sauté ginger and garlic.', 'Add chicken and cook.', 'Add rice and water, simmer until rice is soft.', 'Season with fish sauce.', 'Garnish with spring onions and calamansi.']), calories: 380 },
  { name: 'Goto (Beef Tripe Porridge)', suggestedFor: '["breakfast","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'hard', emoji: '🥣', ingredients: JSON.stringify([{ name: 'Beef tripe', quantity: '300g' }, { name: 'Rice', quantity: '1 cup' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Fish sauce', quantity: '2 tbsp' }, { name: 'Calmasi', quantity: 'for serving' }]), steps: JSON.stringify(['Clean and boil tripe until tender, about 1 hour.', 'Cut tripe into small pieces.', 'Cook rice with ginger to make porridge.', 'Add tripe and season with fish sauce.', 'Serve with calamansi and spring onions.']), calories: 400 },
  { name: 'Champorado', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🍫', ingredients: JSON.stringify([{ name: 'Glutinous rice', quantity: '1 cup' }, { name: 'Tablea (cocoa tablets)', quantity: '4 pieces' }, { name: 'Sugar', quantity: '3 tbsp' }, { name: 'Evaporated milk', quantity: 'for drizzling' }]), steps: JSON.stringify(['Boil rice in water until soft.', 'Melt tablea cocoa tablets into the rice.', 'Stir well and add sugar.', 'Serve hot drizzled with evaporated milk.']), calories: 350 },
  { name: 'Pandesal', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 120, difficulty: 'medium', emoji: '🥖', ingredients: JSON.stringify([{ name: 'Flour', quantity: '3 cups' }, { name: 'Yeast', quantity: '1 packet' }, { name: 'Sugar', quantity: '1/2 cup' }, { name: 'Egg', quantity: '1' }, { name: 'Bread crumbs', quantity: 'for coating' }]), steps: JSON.stringify(['Mix flour, yeast, sugar, and egg to form dough.', 'Let dough rise for 1 hour.', 'Shape into small rolls and coat with bread crumbs.', 'Let rise again for 30 minutes.', 'Bake until golden.']), calories: 150 },
  { name: 'Pan de Coco', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 120, difficulty: 'medium', emoji: '🥥', ingredients: JSON.stringify([{ name: 'Flour', quantity: '3 cups' }, { name: 'Yeast', quantity: '1 packet' }, { name: 'Coconut', quantity: '1 cup, grated' }, { name: 'Sugar', quantity: '1/2 cup' }]), steps: JSON.stringify(['Make dough and let rise.', 'Mix grated coconut with sugar for filling.', 'Fill dough balls with coconut mixture.', 'Let rise again.', 'Bake until golden brown.']), calories: 200 },
  { name: 'Ensaymada', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 120, difficulty: 'medium', emoji: '🧈', ingredients: JSON.stringify([{ name: 'Flour', quantity: '3 cups' }, { name: 'Butter', quantity: '1/2 cup' }, { name: 'Sugar', quantity: '1/2 cup' }, { name: 'Eggs', quantity: '2' }, { name: 'Grated cheese', quantity: 'for topping' }]), steps: JSON.stringify(['Make enriched dough with butter and eggs.', 'Let rise for 1 hour.', 'Shape into buns, let rise again.', 'Bake until golden.', 'Brush with butter and top with sugar and cheese.']), calories: 280 },
  { name: 'Bibingka', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🍚', ingredients: JSON.stringify([{ name: 'Rice flour', quantity: '2 cups' }, { name: 'Coconut milk', quantity: '1 cup' }, { name: 'Sugar', quantity: '1/2 cup' }, { name: 'Egg', quantity: '2' }, { name: 'Salted egg', quantity: '1, sliced' }]), steps: JSON.stringify(['Mix rice flour, coconut milk, sugar, and eggs.', 'Pour into banana leaf-lined pan.', 'Top with salted egg slices.', 'Bake until golden.', 'Brush with butter and top with grated coconut.']), calories: 220 },
  { name: 'Puto (Steamed Rice Cakes)', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 30, difficulty: 'easy', emoji: '🍥', ingredients: JSON.stringify([{ name: 'Rice flour', quantity: '2 cups' }, { name: 'Sugar', quantity: '1/2 cup' }, { name: 'Baking powder', quantity: '1 tsp' }, { name: 'Coconut milk', quantity: '1 cup' }, { name: 'Cheese', quantity: 'for topping' }]), steps: JSON.stringify(['Mix dry ingredients.', 'Add coconut milk and stir.', 'Pour into puto molds.', 'Steam for 15 minutes.', 'Top with grated cheese.']), calories: 180 },
  { name: 'Biko', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 40, difficulty: 'easy', emoji: '🍚', ingredients: JSON.stringify([{ name: 'Glutinous rice', quantity: '2 cups' }, { name: 'Coconut milk', quantity: '2 cups' }, { name: 'Brown sugar', quantity: '1 cup' }, { name: 'Salt', quantity: 'pinch' }]), steps: JSON.stringify(['Cook glutinous rice in coconut milk until tender.', 'Add brown sugar and stir until caramelized.', 'Pour into a greased pan.', 'Press flat and let cool.', 'Slice and serve.']), calories: 300 },
  { name: 'Suman (Sticky Rice in Banana Leaf)', suggestedFor: '["breakfast","snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🍃', ingredients: JSON.stringify([{ name: 'Glutinous rice', quantity: '2 cups' }, { name: 'Coconut milk', quantity: '1 cup' }, { name: 'Salt', quantity: '1/2 tsp' }, { name: 'Banana leaves', quantity: 'for wrapping' }]), steps: JSON.stringify(['Mix rice with coconut milk and salt.', 'Wrap portions in banana leaves.', 'Steam for 45 minutes.', 'Serve with sugar or mango.']), calories: 250 },
  { name: 'Tortang Giniling', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🥚', ingredients: JSON.stringify([{ name: 'Ground pork', quantity: '200g' }, { name: 'Eggs', quantity: '3' }, { name: 'Carrot', quantity: '1, minced' }, { name: 'Onion', quantity: '1, minced' }]), steps: JSON.stringify(['Sauté onion, carrot, and ground pork.', 'Beat eggs and mix with cooked pork.', 'Pan-fry like an omelette until golden both sides.', 'Serve with rice and ketchup.']), calories: 380 },

  // === LUNCH/DINNER-ORIENTED (47 dishes) ===
  { name: 'Sinigang na Baboy', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Pork belly', quantity: '500g' }, { name: 'Tamarind mix', quantity: '1 packet' }, { name: 'Kangkong (water spinach)', quantity: '1 bunch' }, { name: 'Tomato', quantity: '2' }, { name: 'Radish', quantity: '1' }, { name: 'Eggplant', quantity: '1' }]), steps: JSON.stringify(['Boil pork in water until tender.', 'Add tomatoes and tamarind mix.', 'Add radish and eggplant.', 'Add kangkong at the end.', 'Season with fish sauce and serve.']), calories: 450 },
  { name: 'Sinigang na Hipon', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Shrimp', quantity: '500g' }, { name: 'Tamarind mix', quantity: '1 packet' }, { name: 'Kangkong', quantity: '1 bunch' }, { name: 'Tomato', quantity: '2' }, { name: 'Radish', quantity: '1' }]), steps: JSON.stringify(['Boil water with tomatoes.', 'Add tamarind mix.', 'Add radish, then shrimp.', 'Add kangkong at the end.', 'Season and serve.']), calories: 280 },
  { name: 'Sinigang na Bangus', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Milkfish (bangus)', quantity: '1 whole' }, { name: 'Tamarind mix', quantity: '1 packet' }, { name: 'Kangkong', quantity: '1 bunch' }, { name: 'Tomato', quantity: '2' }, { name: 'Okra', quantity: '6 pieces' }]), steps: JSON.stringify(['Boil water with tomatoes and tamarind.', 'Add okra.', 'Add bangus and simmer until cooked.', 'Add kangkong.', 'Season and serve.']), calories: 350 },
  { name: 'Nilagang Baka', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef shank', quantity: '500g' }, { name: 'Cabbage', quantity: '1/4 head' }, { name: 'Potatoes', quantity: '2' }, { name: 'Corn', quantity: '1 ear' }, { name: 'Fish sauce', quantity: '2 tbsp' }]), steps: JSON.stringify(['Boil beef shank until tender, about 1 hour.', 'Add corn and potatoes.', 'Add cabbage at the end.', 'Season with fish sauce.', 'Serve with rice.']), calories: 480 },
  { name: 'Bulalo', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 120, difficulty: 'hard', emoji: '🦴', ingredients: JSON.stringify([{ name: 'Beef marrow bones', quantity: '1kg' }, { name: 'Corn', quantity: '2 ears' }, { name: 'Cabbage', quantity: '1/4 head' }, { name: 'Fish sauce', quantity: 'to taste' }]), steps: JSON.stringify(['Boil marrow bones for 2 hours until very tender.', 'Add corn.', 'Add cabbage at the end.', 'Season with fish sauce.', 'Serve hot with rice.']), calories: 550 },
  { name: 'Tinola', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'easy', emoji: '🍲', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '500g' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Papaya', quantity: '1 green' }, { name: 'Malunggay leaves', quantity: '1 cup' }, { name: 'Fish sauce', quantity: '2 tbsp' }]), steps: JSON.stringify(['Sauté ginger and garlic.', 'Add chicken and cook.', 'Add water and bring to boil.', 'Add green papaya.', 'Add malunggay leaves and serve.']), calories: 350 },
  { name: 'Paksiw na Lechon', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Leftover lechon (roast pork)', quantity: '500g' }, { name: 'Vinegar', quantity: '1/2 cup' }, { name: 'Garlic', quantity: '4 cloves' }, { name: 'Peppercorns', quantity: '1 tsp' }, { name: 'Liver spread', quantity: '2 tbsp' }]), steps: JSON.stringify(['Combine all ingredients in a pot.', 'Simmer for 30 minutes.', 'Serve hot with rice.']), calories: 500 },
  { name: 'Paksiw na Isda', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 25, difficulty: 'easy', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Fish (any white fish)', quantity: '500g' }, { name: 'Vinegar', quantity: '1/2 cup' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Peppercorns', quantity: '1 tsp' }]), steps: JSON.stringify(['Combine vinegar, garlic, ginger, and peppercorns.', 'Add fish and simmer for 20 minutes.', 'Do not stir to avoid fish breaking.', 'Serve with rice.']), calories: 250 },
  { name: 'Kare-Kare', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 120, difficulty: 'hard', emoji: '🥜', ingredients: JSON.stringify([{ name: 'Oxtail', quantity: '500g' }, { name: 'Peanut butter', quantity: '1/2 cup' }, { name: 'Bagoong (shrimp paste)', quantity: 'for serving' }, { name: 'Eggplant', quantity: '1' }, { name: 'String beans', quantity: '1 cup' }, { name: 'Banana blossom', quantity: '1' }]), steps: JSON.stringify(['Boil oxtail until very tender.', 'Dissolve peanut butter in broth.', 'Add vegetables and cook.', 'Serve with bagoong on the side.']), calories: 600 },
  { name: 'Bicol Express', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'medium', emoji: '🌶️', ingredients: JSON.stringify([{ name: 'Pork belly', quantity: '400g' }, { name: 'Coconut milk', quantity: '2 cups' }, { name: 'Chili peppers', quantity: '5 pieces' }, { name: 'Shrimp paste', quantity: '2 tbsp' }, { name: 'Garlic', quantity: '3 cloves' }]), steps: JSON.stringify(['Sauté garlic and pork.', 'Add shrimp paste and cook.', 'Add coconut milk and chili.', 'Simmer until oil separates.', 'Serve hot.']), calories: 550 },
  { name: 'Laing', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🍃', ingredients: JSON.stringify([{ name: 'Dried taro leaves', quantity: '200g' }, { name: 'Coconut milk', quantity: '2 cups' }, { name: 'Chili', quantity: '3 pieces' }, { name: 'Shrimp paste', quantity: '2 tbsp' }, { name: 'Pork (optional)', quantity: '100g' }]), steps: JSON.stringify(['Soak dried taro leaves.', 'Simmer coconut milk with shrimp paste and chili.', 'Add taro leaves and cook for 30 minutes.', 'Add pork if using.', 'Serve with rice.']), calories: 350 },
  { name: 'Caldereta', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef', quantity: '500g' }, { name: 'Tomato sauce', quantity: '1 cup' }, { name: 'Liver spread', quantity: '3 tbsp' }, { name: 'Potatoes', quantity: '2' }, { name: 'Bell pepper', quantity: '1' }, { name: 'Cheese', quantity: 'for topping' }]), steps: JSON.stringify(['Sauté beef until browned.', 'Add tomato sauce and simmer until tender.', 'Add liver spread and potatoes.', 'Add bell peppers.', 'Top with cheese and serve.']), calories: 520 },
  { name: 'Mechado', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef', quantity: '500g' }, { name: 'Tomato sauce', quantity: '1 cup' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Potatoes', quantity: '2' }, { name: 'Bay leaves', quantity: '2' }]), steps: JSON.stringify(['Marinate beef in soy sauce.', 'Sauté beef until browned.', 'Add tomato sauce and bay leaves.', 'Simmer until tender.', 'Add potatoes and cook until done.']), calories: 480 },
  { name: 'Menudo', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Pork', quantity: '300g' }, { name: 'Pork liver', quantity: '100g' }, { name: 'Tomato sauce', quantity: '1 cup' }, { name: 'Potatoes', quantity: '2' }, { name: 'Carrots', quantity: '1' }, { name: 'Raisins', quantity: '2 tbsp' }]), steps: JSON.stringify(['Sauté pork until browned.', 'Add tomato sauce and simmer.', 'Add potatoes and carrots.', 'Add liver at the end.', 'Top with raisins and serve.']), calories: 420 },
  { name: 'Afritada', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 50, difficulty: 'medium', emoji: '🍗', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '500g' }, { name: 'Tomato sauce', quantity: '1 cup' }, { name: 'Potatoes', quantity: '2' }, { name: 'Bell pepper', quantity: '1' }, { name: 'Carrots', quantity: '1' }]), steps: JSON.stringify(['Sauté chicken until browned.', 'Add tomato sauce and simmer.', 'Add potatoes and carrots.', 'Add bell peppers.', 'Serve over rice.']), calories: 400 },
  { name: 'Pinakbet', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 30, difficulty: 'easy', emoji: '🥬', ingredients: JSON.stringify([{ name: 'Bitter melon', quantity: '1' }, { name: 'Eggplant', quantity: '1' }, { name: 'Okra', quantity: '6 pieces' }, { name: 'Squash', quantity: '1 cup' }, { name: 'Shrimp paste', quantity: '2 tbsp' }]), steps: JSON.stringify(['Sauté garlic and onion.', 'Add shrimp paste.', 'Add vegetables in order of hardness.', 'Simmer until tender.', 'Serve with rice.']), calories: 180 },
  { name: 'Dinengdeng', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'easy', emoji: '🥬', ingredients: JSON.stringify([{ name: 'Mixed vegetables', quantity: '3 cups' }, { name: 'Fish', quantity: '200g' }, { name: 'Bagoong (shrimp paste)', quantity: '2 tbsp' }, { name: 'Ginger', quantity: '1 thumb' }]), steps: JSON.stringify(['Boil water with ginger and bagoong.', 'Add fish and cook.', 'Add vegetables.', 'Simmer until vegetables are tender.', 'Serve with rice.']), calories: 250 },
  { name: 'Ginisang Monggo', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 40, difficulty: 'easy', emoji: '🫘', ingredients: JSON.stringify([{ name: 'Mung beans', quantity: '1 cup' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Onion', quantity: '1' }, { name: 'Spinach', quantity: '1 cup' }, { name: 'Patis (fish sauce)', quantity: '2 tbsp' }]), steps: JSON.stringify(['Boil mung beans until soft.', 'Sauté garlic and onion.', 'Add cooked mung beans.', 'Add spinach.', 'Season and serve.']), calories: 280 },
  { name: 'Lumpiang Sariwa', suggestedFor: '["lunch","snack"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🥟', ingredients: JSON.stringify([{ name: 'Lumpia wrapper', quantity: '6 sheets' }, { name: 'Shrimp', quantity: '200g' }, { name: 'Tofu', quantity: '1 block' }, { name: 'Bean sprouts', quantity: '1 cup' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Peanut sauce', quantity: 'for topping' }]), steps: JSON.stringify(['Sauté garlic, shrimp, and tofu.', 'Add bean sprouts and cook briefly.', 'Wrap filling in lumpia wrapper.', 'Top with peanut sauce.', 'Serve fresh.']), calories: 300 },
  { name: 'Pancit Canton', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🍜', ingredients: JSON.stringify([{ name: 'Canton noodles', quantity: '500g' }, { name: 'Chicken', quantity: '200g' }, { name: 'Carrots', quantity: '1' }, { name: 'Cabbage', quantity: '1 cup' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Calmasi', quantity: 'for serving' }]), steps: JSON.stringify(['Sauté garlic and chicken.', 'Add vegetables.', 'Add noodles and soy sauce.', 'Toss until well mixed.', 'Serve with calamansi.']), calories: 400 },
  { name: 'Pancit Bihon', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🍜', ingredients: JSON.stringify([{ name: 'Rice noodles', quantity: '500g' }, { name: 'Shrimp', quantity: '200g' }, { name: 'Carrots', quantity: '1' }, { name: 'Cabbage', quantity: '1 cup' }, { name: 'Fish sauce', quantity: '2 tbsp' }]), steps: JSON.stringify(['Soak noodles in water.', 'Sauté garlic, onion, and shrimp.', 'Add vegetables and noodles.', 'Season with fish sauce.', 'Serve hot.']), calories: 350 },
  { name: 'Pancit Malabon', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'hard', emoji: '🍜', ingredients: JSON.stringify([{ name: 'Thick rice noodles', quantity: '500g' }, { name: 'Shrimp', quantity: '200g' }, { name: 'Squid', quantity: '200g' }, { name: 'Tinapa (smoked fish)', quantity: '1 cup' }, { name: 'Annatto oil', quantity: '2 tbsp' }]), steps: JSON.stringify(['Cook noodles and set aside.', 'Sauté shrimp and squid.', 'Prepare annatto oil sauce.', 'Mix noodles with sauce and toppings.', 'Serve with calamansi and eggs.']), calories: 420 },
  { name: 'Chicken Adobo', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '["gluten-free"]', prepTimeMinutes: 40, difficulty: 'easy', emoji: '🍗', ingredients: JSON.stringify([{ name: 'Chicken thighs', quantity: '500g' }, { name: 'Soy sauce', quantity: '1/4 cup' }, { name: 'Vinegar', quantity: '1/4 cup' }, { name: 'Garlic', quantity: '5 cloves' }, { name: 'Bay leaves', quantity: '2' }, { name: 'Pepper', quantity: '1 tsp' }]), steps: JSON.stringify(['Combine chicken with soy sauce, vinegar, garlic, bay leaves, and pepper.', 'Marinate 30 minutes.', 'Bring to a boil then simmer 30 minutes.', 'Optional: pan-fry to brown.', 'Serve over rice.']), calories: 480 },
  { name: 'Pork Adobo', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'easy', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Pork belly', quantity: '500g' }, { name: 'Soy sauce', quantity: '1/4 cup' }, { name: 'Vinegar', quantity: '1/4 cup' }, { name: 'Garlic', quantity: '5 cloves' }, { name: 'Peppercorns', quantity: '1 tsp' }]), steps: JSON.stringify(['Combine pork with all ingredients.', 'Marinate 30 minutes.', 'Simmer until pork is tender and sauce thickens.', 'Serve over rice.']), calories: 550 },
  { name: 'Adobong Puti', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '["gluten-free"]', prepTimeMinutes: 40, difficulty: 'easy', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Pork', quantity: '500g' }, { name: 'Vinegar', quantity: '1/2 cup' }, { name: 'Garlic', quantity: '5 cloves' }, { name: 'Salt', quantity: '1 tsp' }, { name: 'Peppercorns', quantity: '1 tsp' }]), steps: JSON.stringify(['Combine pork with vinegar, garlic, salt, and peppercorns.', 'Simmer until pork is tender.', 'Serve over rice.']), calories: 500 },
  { name: 'Adobong Pusit', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🦑', ingredients: JSON.stringify([{ name: 'Squid', quantity: '500g' }, { name: 'Vinegar', quantity: '1/4 cup' }, { name: 'Soy sauce', quantity: '2 tbsp' }, { name: 'Garlic', quantity: '4 cloves' }, { name: 'Ink sacs', quantity: 'reserved' }]), steps: JSON.stringify(['Clean squid and reserve ink sacs.', 'Sauté garlic.', 'Add squid, vinegar, soy sauce, and ink.', 'Simmer 15 minutes.', 'Serve with rice.']), calories: 300 },
  { name: 'Lechon Kawali', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🥓', ingredients: JSON.stringify([{ name: 'Pork belly', quantity: '500g' }, { name: 'Salt', quantity: '1 tbsp' }, { name: 'Pepper', quantity: '1 tsp' }, { name: 'Bay leaves', quantity: '2' }, { name: 'Oil', quantity: 'for deep frying' }]), steps: JSON.stringify(['Boil pork belly with salt and bay leaves until tender.', 'Let cool and cut into chunks.', 'Deep fry until golden and crispy.', 'Serve with lechon sauce and rice.']), calories: 650 },
  { name: 'Crispy Pata', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 120, difficulty: 'hard', emoji: '🦵', ingredients: JSON.stringify([{ name: 'Whole pork leg', quantity: '1 piece' }, { name: 'Salt', quantity: '2 tbsp' }, { name: 'Peppercorns', quantity: '1 tbsp' }, { name: 'Garlic', quantity: '6 cloves' }, { name: 'Oil', quantity: 'for deep frying' }]), steps: JSON.stringify(['Boil pork leg with aromatics until very tender.', 'Dry thoroughly overnight in fridge.', 'Deep fry until skin is crispy.', 'Serve with soy-vinegar dipping sauce.']), calories: 800 },
  { name: 'Chicharon Bulaklak', suggestedFor: '["snack","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🥓', ingredients: JSON.stringify([{ name: 'Pork ruffles (ruffle fat)', quantity: '500g' }, { name: 'Salt', quantity: '1 tbsp' }, { name: 'Vinegar', quantity: 'for dipping' }, { name: 'Garlic', quantity: '3 cloves' }]), steps: JSON.stringify(['Boil pork ruffles with salt and garlic.', 'Let dry.', 'Deep fry until golden and crispy.', 'Serve with vinegar dipping sauce.']), calories: 450 },
  { name: 'Sisig', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'medium', emoji: '🍳', ingredients: JSON.stringify([{ name: 'Pork face/ear', quantity: '500g' }, { name: 'Onion', quantity: '1, minced' }, { name: 'Chili', quantity: '3 pieces' }, { name: 'Calmasi', quantity: '5 pieces' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Grill or boil pork until cooked.', 'Chop into small pieces.', 'Sauté with onion and chili.', 'Add calamansi and top with egg.', 'Serve sizzling on a hot plate.']), calories: 450 },
  { name: 'Inihaw na Liempo', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 50, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Pork belly', quantity: '500g' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Calmasi', quantity: '5 pieces' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Pepper', quantity: '1 tsp' }]), steps: JSON.stringify(['Marinate pork in soy sauce, calamansi, and garlic.', 'Grill over charcoal until cooked.', 'Baste with marinade.', 'Serve with rice and vinegar dipping.']), calories: 600 },
  { name: 'Inihaw na Manok', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🍗', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '1 whole' }, { name: 'Soy sauce', quantity: '1/2 cup' }, { name: 'Calmasi', quantity: '10 pieces' }, { name: 'Garlic', quantity: '5 cloves' }, { name: 'Lemongrass', quantity: '2 stalks' }]), steps: JSON.stringify(['Marinate chicken in soy sauce, calamansi, garlic, and lemongrass for 2 hours.', 'Grill until fully cooked.', 'Baste with marinade.', 'Serve with rice.']), calories: 450 },
  { name: 'Inihaw na Bangus', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 40, difficulty: 'medium', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Milkfish', quantity: '1 whole' }, { name: 'Tomato', quantity: '2, sliced' }, { name: 'Onion', quantity: '1, sliced' }, { name: 'Calmasi', quantity: '5 pieces' }, { name: 'Salt', quantity: '1 tsp' }]), steps: JSON.stringify(['Clean and split milkfish.', 'Stuff with tomato, onion, and calamansi.', 'Grill until cooked.', 'Serve with rice.']), calories: 380 },
  { name: 'Inihaw na Pusit', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 25, difficulty: 'easy', emoji: '🦑', ingredients: JSON.stringify([{ name: 'Squid', quantity: '500g' }, { name: 'Soy sauce', quantity: '2 tbsp' }, { name: 'Calmasi', quantity: '3 pieces' }, { name: 'Garlic', quantity: '2 cloves' }]), steps: JSON.stringify(['Marinate squid in soy sauce, calamansi, and garlic.', 'Grill 3 minutes per side.', 'Serve immediately.']), calories: 200 },
  { name: 'Daing na Bangus', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Milkfish (boneless)', quantity: '1 piece' }, { name: 'Vinegar', quantity: '1/4 cup' }, { name: 'Garlic', quantity: '4 cloves' }, { name: 'Pepper', quantity: '1 tsp' }]), steps: JSON.stringify(['Marinate milkfish in vinegar, garlic, and pepper.', 'Pan-fry until crispy on both sides.', 'Serve with rice.']), calories: 350 },
  { name: 'Daing na Bisugo', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Threadfin fish (bisugo)', quantity: '2 pieces' }, { name: 'Vinegar', quantity: '1/4 cup' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Salt', quantity: '1 tsp' }]), steps: JSON.stringify(['Marinate fish in vinegar, garlic, and salt.', 'Pan-fry until crispy.', 'Serve with rice.']), calories: 300 },
  { name: 'Tortang Talong', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🥚', ingredients: JSON.stringify([{ name: 'Eggplant', quantity: '1 large' }, { name: 'Egg', quantity: '2' }, { name: 'Salt', quantity: 'to taste' }]), steps: JSON.stringify(['Grill or roast eggplant until skin chars.', 'Peel skin and flatten the flesh.', 'Dip in beaten egg.', 'Pan-fry until golden on both sides.', 'Serve with rice.']), calories: 200 },
  { name: 'Relyenong Bangus', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'hard', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Milkfish', quantity: '1 whole' }, { name: 'Pork', quantity: '200g, ground' }, { name: 'Carrots', quantity: '1, minced' }, { name: 'Onion', quantity: '1, minced' }, { name: 'Egg', quantity: '2' }]), steps: JSON.stringify(['Remove meat from fish while keeping skin intact.', 'Mix fish meat with pork, carrots, onion, and egg.', 'Stuff mixture back into fish skin.', 'Sew or secure opening.', 'Steam then fry until golden.']), calories: 450 },
  { name: 'Embutido', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Ground pork', quantity: '500g' }, { name: 'Egg', quantity: '2' }, { name: 'Carrots', quantity: '1, minced' }, { name: 'Raisins', quantity: '2 tbsp' }, { name: 'Vienna sausage', quantity: '2 pieces' }]), steps: JSON.stringify(['Mix pork with egg, carrots, and raisins.', 'Wrap mixture around sausages.', 'Roll in aluminum foil.', 'Steam for 45 minutes.', 'Slice and serve.']), calories: 400 },
  { name: 'Morcon', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'hard', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef flank', quantity: '500g' }, { name: 'Pork', quantity: '200g, ground' }, { name: 'Carrots', quantity: '1' }, { name: 'Pickles', quantity: '1/4 cup' }, { name: 'Cheese', quantity: '1/2 cup' }]), steps: JSON.stringify(['Pound beef flank flat.', 'Layer with pork, carrots, pickles, and cheese.', 'Roll tightly and tie with string.', 'Braise in tomato sauce for 1 hour.', 'Slice and serve.']), calories: 500 },
  { name: 'Fish Kinilaw', suggestedFor: '["lunch","snack"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Fresh fish (tanigue)', quantity: '300g' }, { name: 'Vinegar', quantity: '1/2 cup' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Onion', quantity: '1' }, { name: 'Chili', quantity: '2 pieces' }]), steps: JSON.stringify(['Cube fresh fish.', 'Soak in vinegar for 10 minutes.', 'Add ginger, onion, and chili.', 'Serve cold.']), calories: 180 },
  { name: 'Kinilaw na Tanigue', suggestedFor: '["lunch","snack"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🐟', ingredients: JSON.stringify([{ name: 'Mackerel (tanigue)', quantity: '300g' }, { name: 'Coconut vinegar', quantity: '1/2 cup' }, { name: 'Ginger', quantity: '1 thumb' }, { name: 'Calmasi', quantity: '5 pieces' }, { name: 'Coconut milk', quantity: '1/4 cup' }]), steps: JSON.stringify(['Cube mackerel.', 'Marinate in vinegar and calamansi.', 'Add ginger, onion, and coconut milk.', 'Serve cold.']), calories: 200 },
  { name: 'Dinuguan', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 50, difficulty: 'medium', emoji: '🥘', ingredients: JSON.stringify([{ name: 'Pork meat', quantity: '300g' }, { name: 'Pork blood', quantity: '1 cup' }, { name: 'Vinegar', quantity: '3 tbsp' }, { name: 'Garlic', quantity: '4 cloves' }, { name: 'Chili', quantity: '2 pieces' }]), steps: JSON.stringify(['Sauté garlic and pork.', 'Add vinegar and let boil.', 'Add pork blood and stir continuously.', 'Season with chili and salt.', 'Serve with puto or rice.']), calories: 400 },
  { name: 'Batchoy', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🍜', ingredients: JSON.stringify([{ name: 'Miki noodles', quantity: '500g' }, { name: 'Pork offal', quantity: '200g' }, { name: 'Shrimp', quantity: '100g' }, { name: 'Chicharon', quantity: '1/2 cup' }, { name: 'Egg', quantity: '1' }]), steps: JSON.stringify(['Boil pork offal until tender.', 'Add noodles and shrimp.', 'Top with crushed chicharon.', 'Add raw egg and mix.', 'Serve hot.']), calories: 500 },
  { name: 'Pares', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 90, difficulty: 'medium', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef', quantity: '500g' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Garlic', quantity: '4 cloves' }, { name: 'Star anise', quantity: '2 pieces' }, { name: 'Rice', quantity: 'for serving' }]), steps: JSON.stringify(['Boil beef with soy sauce, garlic, and star anise.', 'Simmer until tender.', 'Serve beef over rice.', 'Pour broth on the side.']), calories: 520 },
  { name: 'Beef Kansi', suggestedFor: '["lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 120, difficulty: 'hard', emoji: '🥩', ingredients: JSON.stringify([{ name: 'Beef bone marrow', quantity: '1kg' }, { name: 'Ginger', quantity: '2 thumbs' }, { name: 'Lemongrass', quantity: '2 stalks' }, { name: 'Sour fruit (batuan or kamias)', quantity: '4 pieces' }]), steps: JSON.stringify(['Boil bone marrow for 2 hours.', 'Add ginger, lemongrass, and sour fruit.', 'Simmer until broth is flavorful.', 'Serve with rice.']), calories: 450 },
  { name: 'Fried Chicken (Filipino-style)', suggestedFor: '["breakfast","lunch","dinner"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 35, difficulty: 'easy', emoji: '🍗', ingredients: JSON.stringify([{ name: 'Chicken', quantity: '500g' }, { name: 'Soy sauce', quantity: '3 tbsp' }, { name: 'Calmasi', quantity: '5 pieces' }, { name: 'Garlic', quantity: '3 cloves' }, { name: 'Oil', quantity: 'for frying' }]), steps: JSON.stringify(['Marinate chicken in soy sauce, calamansi, and garlic.', 'Deep fry until golden and crispy.', 'Serve with rice and ketchup.']), calories: 450 },

  // === SNACK-ORIENTED (12 dishes) ===
  { name: 'Lumpiang Shanghai', suggestedFor: '["snack","lunch"]', cuisine: 'Filipino', dietaryTags: '[]', prepTimeMinutes: 30, difficulty: 'medium', emoji: '🌯', ingredients: JSON.stringify([{ name: 'Ground pork', quantity: '250g' }, { name: 'Carrot', quantity: '1, minced' }, { name: 'Onion', quantity: '1, minced' }, { name: 'Lumpia wrappers', quantity: '20 sheets' }, { name: 'Egg', quantity: '1, beaten' }]), steps: JSON.stringify(['Mix pork, carrot, and onion.', 'Wrap in lumpia wrappers.', 'Seal with beaten egg.', 'Deep fry until golden.', 'Serve with sweet chili sauce.']), calories: 320 },
  { name: 'Turon', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🍌', ingredients: JSON.stringify([{ name: 'Saba banana', quantity: '4 pieces' }, { name: 'Brown sugar', quantity: '1/2 cup' }, { name: 'Lumpia wrapper', quantity: '4 sheets' }, { name: 'Jackfruit (optional)', quantity: '1/4 cup' }]), steps: JSON.stringify(['Slice banana and roll in brown sugar.', 'Wrap in lumpia wrapper with jackfruit.', 'Deep fry until caramelized.', 'Serve as dessert or snack.']), calories: 250 },
  { name: 'Maruya', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🍌', ingredients: JSON.stringify([{ name: 'Saba banana', quantity: '4 pieces' }, { name: 'Flour', quantity: '1/2 cup' }, { name: 'Sugar', quantity: '2 tbsp' }, { name: 'Egg', quantity: '1' }, { name: 'Oil', quantity: 'for frying' }]), steps: JSON.stringify(['Slice banana lengthwise.', 'Mix flour, egg, and sugar into batter.', 'Dip banana slices in batter.', 'Deep fry until golden.', 'Top with sugar.']), calories: 200 },
  { name: 'Camote Q', suggestedFor: '["snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🍠', ingredients: JSON.stringify([{ name: 'Sweet potato', quantity: '2 large' }, { name: 'Brown sugar', quantity: '1/2 cup' }, { name: 'Oil', quantity: 'for frying' }]), steps: JSON.stringify(['Peel and cube sweet potato.', 'Deep fry until tender.', 'Coat with caramelized brown sugar.', 'Serve on sticks.']), calories: 300 },
  { name: 'Banana Cue', suggestedFor: '["snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 15, difficulty: 'easy', emoji: '🍌', ingredients: JSON.stringify([{ name: 'Saba banana', quantity: '4 pieces' }, { name: 'Brown sugar', quantity: '1/2 cup' }, { name: 'Oil', quantity: 'for frying' }]), steps: JSON.stringify(['Peel bananas.', 'Roll in brown sugar.', 'Deep fry until caramelized.', 'Serve on bamboo skewers.']), calories: 280 },
  { name: 'Ginataang Bilo-Bilo', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 30, difficulty: 'easy', emoji: '🥥', ingredients: JSON.stringify([{ name: 'Glutinous rice flour', quantity: '1 cup' }, { name: 'Coconut milk', quantity: '2 cups' }, { name: 'Saba banana', quantity: '2' }, { name: 'Jackfruit', quantity: '1/2 cup' }, { name: 'Tapioca pearls', quantity: '1/4 cup' }, { name: 'Sugar', quantity: '1/2 cup' }]), steps: JSON.stringify(['Make bilo-bilo balls from rice flour and water.', 'Boil coconut milk with sugar.', 'Add tapioca pearls and bilo-bilo.', 'Add sliced banana and jackfruit.', 'Serve warm.']), calories: 350 },
  { name: 'Ginataang Halo-Halo', suggestedFor: '["snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 20, difficulty: 'easy', emoji: '🥥', ingredients: JSON.stringify([{ name: 'Coconut milk', quantity: '2 cups' }, { name: 'Sweet potato', quantity: '1' }, { name: 'Saba banana', quantity: '2' }, { name: 'Tapioca pearls', quantity: '1/4 cup' }, { name: 'Sugar', quantity: '1/2 cup' }]), steps: JSON.stringify(['Boil coconut milk with sugar.', 'Add sweet potato and cook until tender.', 'Add saba banana.', 'Add cooked tapioca pearls.', 'Serve warm or cold.']), calories: 300 },
  { name: 'Halo-Halo', suggestedFor: '["snack"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 10, difficulty: 'easy', emoji: '🍨', ingredients: JSON.stringify([{ name: 'Shaved ice', quantity: '2 cups' }, { name: 'Evaporated milk', quantity: '1/2 cup' }, { name: 'Ube halaya', quantity: '2 tbsp' }, { name: 'Leche flan', quantity: '1 slice' }, { name: 'Macapuno', quantity: '2 tbsp' }, { name: 'Pinipig', quantity: '1 tbsp' }]), steps: JSON.stringify(['Fill glass with shaved ice.', 'Top with ube, leche flan, macapuno, and pinipig.', 'Drizzle with evaporated milk.', 'Mix before eating.']), calories: 400 },
  { name: 'Leche Flan', suggestedFor: '["snack","dessert"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 60, difficulty: 'medium', emoji: '🍮', ingredients: JSON.stringify([{ name: 'Egg yolks', quantity: '10' }, { name: 'Condensed milk', quantity: '1 can' }, { name: 'Evaporated milk', quantity: '1 can' }, { name: 'Sugar', quantity: '1 cup, for caramel' }]), steps: JSON.stringify(['Make caramel by melting sugar in a pan.', 'Mix egg yolks, condensed milk, and evaporated milk.', 'Pour into caramel-lined pan.', 'Steam for 45 minutes.', 'Chill before serving.']), calories: 350 },
  { name: 'Ube Halaya', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 45, difficulty: 'medium', emoji: '🟣', ingredients: JSON.stringify([{ name: 'Purple yam (ube)', quantity: '500g' }, { name: 'Coconut milk', quantity: '1 cup' }, { name: 'Condensed milk', quantity: '1/2 cup' }, { name: 'Butter', quantity: '2 tbsp' }]), steps: JSON.stringify(['Boil and mash purple yam.', 'Mix with coconut milk and condensed milk.', 'Cook over low heat, stirring constantly.', 'Add butter and mix until thick.', 'Chill and serve.']), calories: 280 },
  { name: 'Puto Bumbong', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 60, difficulty: 'hard', emoji: '🟣', ingredients: JSON.stringify([{ name: 'Purple rice (pirurutong)', quantity: '2 cups' }, { name: 'Coconut', quantity: 'shredded, for topping' }, { name: 'Butter', quantity: '2 tbsp' }, { name: 'Sugar', quantity: '1/2 cup' }]), steps: JSON.stringify(['Soak purple rice overnight.', 'Grind rice into a paste.', 'Press into bamboo tubes.', 'Steam for 20 minutes.', 'Top with butter, coconut, and sugar.']), calories: 250 },
  { name: 'Sapin-Sapin', suggestedFor: '["snack","breakfast"]', cuisine: 'Filipino', dietaryTags: '["vegetarian"]', prepTimeMinutes: 50, difficulty: 'medium', emoji: '🟣', ingredients: JSON.stringify([{ name: 'Glutinous rice flour', quantity: '2 cups' }, { name: 'Coconut milk', quantity: '2 cups' }, { name: 'Sugar', quantity: '1 cup' }, { name: 'Ube extract', quantity: '1 tsp' }, { name: 'Macapuno', quantity: '1/2 cup' }]), steps: JSON.stringify(['Mix rice flour, coconut milk, and sugar.', 'Divide into 3 portions and color each.', 'Steam each layer one at a time for 10 minutes each.', 'Top with macapuno.', 'Chill and slice.']), calories: 350 },
];

export async function seedDatabase() {
  const count = await db.meals.count();
  if (count > 0) return;

  const mealsToAdd = seedMeals.map(meal => ({
    ...meal,
    photoPath: null as string | null,
    youtubeLink: null as string | null,
    isFavorite: 0,
    isCustom: 0,
  }));

  await db.meals.bulkAdd(mealsToAdd as any);

  console.log(`✅ Seeded ${mealsToAdd.length} Filipino dishes`);
}
